# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popisi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podrobnosti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('nivo', models.CharField(choices=[('NIZEK', 'Določila, minimalna vsebina '), ('SREDNJI', 'Določila, običajna vsebina'), ('VISOK', 'Določila, podrobna vsebina')], default=popisi.models.NivoDolocilaDel('Določila, običajna vsebina'), max_length=10)),
                ('predmet', models.TextField(blank=True)),
                ('osnovni_materiali', models.TextField(blank=True)),
                ('osnove_za_izvedbo', models.TextField(blank=True)),
                ('nacin_izvedbe', models.TextField(blank=True)),
                ('kakovost_izvedenih_del', models.TextField(blank=True)),
                ('preverjanje_kakovosti_izvedenih_del', models.TextField(blank=True)),
                ('merjenje_prevzem_obracun', models.TextField(blank=True)),
                ('datoteka', models.ManyToManyField(to='podrobnosti.Datoteka')),
                ('dokumentacija', models.ManyToManyField(to='podrobnosti.Dokumentacija')),
                ('slika', models.ManyToManyField(to='podrobnosti.Slika')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('enota_mere', models.CharField(max_length=10)),
                ('dela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela')),
                ('merilo', models.ManyToManyField(to='podrobnosti.Merilo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VrstaDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('skupina_del', models.CharField(choices=[('GRADBENA', 'Gradbena dela'), ('OBRTNISKA', 'Obrtniška dela'), ('STROJNE', 'Strojne instalacije'), ('ELEKTRO', 'Električne instalacije'), ('ZUNANJA', 'Zunanja ureditev')], default=popisi.models.SkupinaDel('Gradbena dela'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dela',
            name='vrsta_del',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.VrstaDel'),
        ),
    ]
