# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popisi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podrobnosti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopisnaPostavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('podrobnost', models.ManyToManyField(to='podrobnosti.Podrobnost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('enota_mere', models.CharField(max_length=10)),
                ('dela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VrstaDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('skupina_del', models.CharField(choices=[('GRADBENA', 'Gradbena dela'), ('OBRTNISKA', 'Obrtniška dela'), ('STROJNE', 'Strojne instalacije'), ('ELEKTRO', 'Električne instalacije'), ('ZUNANJA', 'Zunanja ureditev')], default=popisi.models.SkupinaDel('Gradbena dela'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='popisnapostavka',
            name='postavka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Postavka'),
        ),
        migrations.AddField(
            model_name='dela',
            name='vrsta_del',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.VrstaDel'),
        ),
    ]
