# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popisnapostavka',
            old_name='podrobnost',
            new_name='podrobnost1',
        ),
    ]
