# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0012_specifikacija_tekst_za_popis'),
        ('popisi', '0002_auto_20180331_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='popisnapostavka',
            name='podrobnost2',
            field=models.ManyToManyField(to='podrobnosti.Podrobnost2'),
        ),
    ]
