# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import podrobnosti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datoteka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('datoteka', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dokumentacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('naslov', models.TextField(blank=True)),
                ('zvrst', models.CharField(choices=[('STANDARD', 'Standard'), ('TS', 'Tehnična specifikacija'), ('TP', 'Tehnični predpis'), ('PRAVILNIK', 'Pravilnik'), ('ZNANOST', 'Znanostvena knjiga'), ('PRAKSA', 'Gradbena praksa'), ('SMERNICE', 'Smernice'), ('PRIPOROCILA', 'Priporocila')], default=podrobnosti.models.Zvrst('Standard'), max_length=30)),
                ('komentar', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('izhodisce', models.CharField(choices=[('ZAKON', 'Zahtevano z zakonom'), ('STROKA', 'Pravila stroke'), ('PRAKSA', 'Gradbena praksa'), ('ZNANOST', 'Znanstvena dognanja'), ('ZDRUZENJA', 'Priporočila združenj'), ('IZVAJALCI', 'Priporočila izvajalcev')], default=podrobnosti.models.Izhodisce('Pravila stroke'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeriloOsnova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeriloSkupina1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podlaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('komentar', models.TextField()),
                ('dokumentacija', models.ManyToManyField(to='podrobnosti.Dokumentacija')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podrobnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('komentar', models.TextField(blank=True)),
                ('merilo', models.ManyToManyField(to='podrobnosti.Merilo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('podrocje', models.CharField(choices=[('MATERIAL', 'Lastnosti materiala'), ('IZDELEK', 'Lastnosti izdelka'), ('PROCES', 'Delovni postopki'), ('VARNOST', 'Varnostne zahteve'), ('SPLOSNO', 'Splošno')], default=podrobnosti.models.Podrocje('Lastnosti materiala'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='podlaga',
            name='predmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Predmet'),
        ),
        migrations.AddField(
            model_name='podlaga',
            name='slika',
            field=models.ManyToManyField(to='podrobnosti.Slika'),
        ),
        migrations.AddField(
            model_name='merilo',
            name='merilo_osnova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podrobnosti.MeriloOsnova'),
        ),
        migrations.AddField(
            model_name='merilo',
            name='merilo_skupina1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.MeriloSkupina1'),
        ),
        migrations.AddField(
            model_name='merilo',
            name='podlaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Podlaga'),
        ),
    ]
