# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import podrobnosti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datoteka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('datoteka', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dokumentacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('naslov', models.TextField(blank=True)),
                ('zvrst', models.CharField(choices=[('STANDARD', 'Standard'), ('TS', 'Tehnična specifikacija'), ('TP', 'Tehnični predpis'), ('PRAVILNIK', 'Pravilnik'), ('ZNANOST', 'Znanostvena knjiga'), ('PRAKSA', 'Gradbena praksa'), ('SMERNICE', 'Smernice'), ('PRIPOROCILA', 'Priporocila')], default=podrobnosti.models.Zvrst('Standard'), max_length=30)),
                ('komentar', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['stevilka'],
            },
        ),
        migrations.CreateModel(
            name='PodlagaMerila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('izhodisce', models.CharField(choices=[('ZAKON', 'Zahtevano z zakonom'), ('STROKA', 'Pravila stroke'), ('PRAKSA', 'Gradbena praksa'), ('ZNANOST', 'Znanstvena dognanja'), ('ZDRUZENJA', 'Priporočila združenj'), ('IZVAJALCI', 'Priporočila izvajalcev')], default=podrobnosti.models.Izhodisce('Pravila stroke'), max_length=10)),
                ('komentar', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podrobnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('tekst_za_popis', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['merilo__stevilka'],
            },
        ),
        migrations.CreateModel(
            name='PredmetMerila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('podrocje', models.CharField(choices=[('MATERIAL', 'Lastnosti materiala'), ('IZDELEK', 'Lastnosti izdelka'), ('PROCES', 'Delovni postopki'), ('VARNOST', 'Varnostne zahteve'), ('SPLOSNO', 'Splošno')], default=podrobnosti.models.Podrocje('Lastnosti materiala'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
