# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import podrobnosti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gradivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('slika', models.ImageField(blank=True, upload_to='')),
                ('tekst_file', models.FileField(blank=True, upload_to='')),
                ('namen', models.CharField(choices=[('VIR', 'Vir'), ('SPECIFIKACIJA', 'Specifikacija'), ('SEGMENT', 'Segment')], default=podrobnosti.models.Namen('Specifikacija'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podrobnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('komentar', models.TextField(blank=True)),
                ('tekst_za_popis', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['specifikacija__stevilka'],
            },
        ),
        migrations.CreateModel(
            name='Poglavje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('predmet', models.CharField(choices=[('MATERIAL', 'Lastnosti materiala'), ('IZDELEK', 'Lastnosti izdelka'), ('PROCES', 'Opis delovnih postopkov'), ('VARNOST', 'Varnostne zahteve'), ('SPLOSNO', 'Splošno')], default=podrobnosti.models.Predmet('Lastnosti materiala'), max_length=10)),
            ],
            options={
                'ordering': ['stevilka'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('tekst_za_popis', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specifikacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('tip', models.CharField(choices=[('POPIS', 'Popis'), ('DOLOCILO', 'Dolocilo')], default=podrobnosti.models.Tip('Popis'), max_length=10)),
                ('podlaga', models.CharField(choices=[('ZAKON', 'Zakonodaja'), ('STROKA', 'Pravila stroke'), ('PRAKSA', 'Gradbena praksa'), ('ZNANOST', 'Znanstvena dognanja'), ('ZDRUZENJA', 'Priporočila združenj'), ('IZVAJALCI', 'Priporočila izvajalcev')], default=podrobnosti.models.Podlaga('Pravila stroke'), max_length=10)),
                ('komentar', models.TextField(blank=True)),
                ('gradivo', models.ManyToManyField(blank=True, to='podrobnosti.Gradivo')),
                ('poglavje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Poglavje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('naslov', models.TextField(blank=True)),
                ('zvrst', models.CharField(choices=[('STANDARD', 'Standard'), ('TS', 'Tehnična specifikacija'), ('TP', 'Tehnični predpis'), ('PRAVILNIK', 'Pravilnik'), ('ZNANOST', 'Znanostvena knjiga'), ('PRAKSA', 'Gradbena praksa'), ('SMERNICE', 'Smernice'), ('PRIPOROCILA', 'Priporocila')], default=podrobnosti.models.Zvrst('Standard'), max_length=30)),
                ('komentar', models.TextField(blank=True)),
                ('gradivo', models.ManyToManyField(blank=True, to='podrobnosti.Gradivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='vir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Vir'),
        ),
    ]
