# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
        ('podrobnosti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Segment',
            new_name='Odsek',
        ),
        migrations.RemoveField(
            model_name='specifikacija',
            name='vir',
        ),
        migrations.RemoveField(
            model_name='vir',
            name='gradivo',
        ),
        migrations.AddField(
            model_name='gradivo',
            name='vir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Vir'),
        ),
        migrations.AddField(
            model_name='podrobnost',
            name='odsek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Odsek'),
        ),
        migrations.AddField(
            model_name='podrobnost',
            name='specifikacija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Specifikacija'),
        ),
        migrations.AddField(
            model_name='poglavje',
            name='dela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela'),
        ),
        migrations.AddField(
            model_name='vir',
            name='tekst_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gradivo',
            name='namen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Namen'),
        ),
    ]
