# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podrobnosti', '0001_initial'),
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poglavje',
            name='dela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela'),
        ),
        migrations.AddField(
            model_name='podrobnost',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Segment'),
        ),
        migrations.AddField(
            model_name='podrobnost',
            name='specifikacija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Specifikacija'),
        ),
    ]
