# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podrobnosti', '0001_initial'),
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meriloosnova',
            name='dela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='popisi.Dela'),
        ),
        migrations.AddField(
            model_name='merilo',
            name='merilo_osnova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podrobnosti.MeriloOsnova'),
        ),
        migrations.AddField(
            model_name='merilo',
            name='merilo_skupina1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.MeriloSkupina1'),
        ),
        migrations.AddField(
            model_name='merilo',
            name='podlaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Podlaga'),
        ),
    ]
