# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('popisi', '0001_initial'),
        ('podrobnosti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poglavje',
            name='dela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela'),
        ),
        migrations.AddField(
            model_name='podskupina',
            name='specifikacija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Specifikacija'),
        ),
        migrations.AddField(
            model_name='podrobnost',
            name='podskupina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Podskupina'),
        ),
        migrations.AddField(
            model_name='dokumentacija',
            name='datoteka',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Datoteka'),
        ),
        migrations.AddField(
            model_name='dokumentacija',
            name='image',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Slika'),
        ),
    ]
