# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_auto_20180226_1832'),
        ('podrobnosti', '0002_auto_20180223_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datoteka',
        ),
        migrations.AlterModelOptions(
            name='merilo',
            options={'ordering': ['podlaga_merila__stevilka']},
        ),
        migrations.AlterModelOptions(
            name='podrobnost',
            options={'ordering': ['merilo__podlaga_merila__stevilka']},
        ),
        migrations.RemoveField(
            model_name='podlagamerila',
            name='slika',
        ),
        migrations.AddField(
            model_name='dokumentacija',
            name='datoteka',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dokumentacija',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Slika',
        ),
    ]
