# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0002_auto_20180322_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='gradivo',
            name='namen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Namen'),
        ),
    ]
