# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0002_auto_20180328_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='odsek',
            name='gs',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
