# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0003_auto_20180322_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifikacija',
            name='vir',
        ),
        migrations.RemoveField(
            model_name='vir',
            name='gradivo',
        ),
        migrations.AddField(
            model_name='gradivo',
            name='vir',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Vir'),
        ),
        migrations.AddField(
            model_name='vir',
            name='tekst_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
