# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0003_auto_20180318_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podrobnost',
            name='podskupina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Podskupina'),
        ),
        migrations.AlterField(
            model_name='podrobnost',
            name='specifikacija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Specifikacija'),
        ),
    ]
