# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0003_odsek_gs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odsek',
            name='gs',
        ),
    ]
