# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import podrobnosti.models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0004_auto_20180226_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='podrobnost',
            name='tip',
            field=models.CharField(choices=[('POPIS', 'Popisna podrobnost'), ('DOLOCILO', 'Dolocilo')], default=podrobnosti.models.Tip('Popisna podrobnost'), max_length=10),
        ),
    ]
