# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0004_auto_20180318_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoteka',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dokumentacija',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podrobnost',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podskupina',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='poglavje',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slika',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='specifikacija',
            name='tekst',
            field=models.CharField(max_length=500),
        ),
    ]
