# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0004_remove_odsek_gs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odsek1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('tekst_za_popis', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
