# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0004_auto_20180322_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradivo',
            name='vir',
        ),
        migrations.AddField(
            model_name='gradivo',
            name='vir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Vir'),
        ),
    ]
