# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0005_auto_20180323_0707'),
        ('podrobnosti', '0002_auto_20180326_1937'),
        ('podrobnosti', '0002_auto_20180327_1444'),
    ]

    operations = [
    ]
