# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0005_odsek1'),
    ]

    operations = [
        migrations.AddField(
            model_name='podrobnost',
            name='odsek1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Odsek1'),
        ),
    ]
