# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0005_auto_20180318_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentacija',
            name='komentar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specifikacija',
            name='komentar',
            field=models.TextField(blank=True),
        ),
    ]
