# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0006_podrobnost_odsek1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podrobnost',
            name='odsek1',
        ),
        migrations.DeleteModel(
            name='Odsek1',
        ),
    ]
