# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0006_auto_20180318_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podskupina',
            new_name='Segment',
        ),
        migrations.AlterModelOptions(
            name='poglavje',
            options={'ordering': ['stevilka']},
        ),
        migrations.RemoveField(
            model_name='podrobnost',
            name='podskupina',
        ),
        migrations.AddField(
            model_name='podrobnost',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrobnosti.Segment'),
        ),
    ]
