# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import podrobnosti.models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
        ('podrobnosti', '0007_auto_20180328_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podrobnost',
            options={'ordering': ['specifikacija__tip', 'specifikacija__stevilka', 'stevilka']},
        ),
        migrations.RemoveField(
            model_name='poglavje',
            name='dela',
        ),
        migrations.RemoveField(
            model_name='poglavje',
            name='predmet',
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='dela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela'),
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='predmet',
            field=models.CharField(choices=[('MATERIAL', 'Lastnosti materiala'), ('IZDELEK', 'Lastnosti izdelka'), ('PROCES', 'Opis delovnih postopkov'), ('VARNOST', 'Varnostne zahteve'), ('SPLOSNO', 'Splošno')], default=podrobnosti.models.Predmet('Lastnosti materiala'), max_length=10),
        ),
    ]
