# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0008_podrobnost_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='tekst_za_popis',
            field=models.TextField(blank=True),
        ),
    ]
