# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0008_auto_20180330_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifikacija',
            name='tekst_za_popis',
            field=models.TextField(blank=True),
        ),
    ]
