# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0008_auto_20180330_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podrobnost',
            name='odsek',
        ),
    ]
