# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0009_specifikacija_tekst_za_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='podrobnost',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
