# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0009_remove_podrobnost_odsek'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podrobnost',
            new_name='Podrobnost1',
        ),
        migrations.RenameModel(
            old_name='Odsek',
            new_name='Podrobnost2',
        ),
    ]
