# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import podrobnosti.models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0009_segment_tekst_za_popis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(blank=True, null=True)),
                ('tekst', models.CharField(max_length=500)),
                ('naslov', models.TextField(blank=True)),
                ('zvrst', models.CharField(choices=[('STANDARD', 'Standard'), ('TS', 'Tehnična specifikacija'), ('TP', 'Tehnični predpis'), ('PRAVILNIK', 'Pravilnik'), ('ZNANOST', 'Znanostvena knjiga'), ('PRAKSA', 'Gradbena praksa'), ('SMERNICE', 'Smernice'), ('PRIPOROCILA', 'Priporocila')], default=podrobnosti.models.Zvrst('Standard'), max_length=30)),
                ('komentar', models.TextField(blank=True)),
                ('datoteka', models.ManyToManyField(blank=True, to='podrobnosti.Datoteka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dokumentacija',
            name='datoteka',
        ),
        migrations.RemoveField(
            model_name='dokumentacija',
            name='image',
        ),
        migrations.RenameField(
            model_name='slika',
            old_name='image',
            new_name='slika',
        ),
        migrations.RemoveField(
            model_name='specifikacija',
            name='dokumentacija',
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='datoteka',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Datoteka'),
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='slika',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Slika'),
        ),
        migrations.AlterField(
            model_name='specifikacija',
            name='podlaga',
            field=models.CharField(choices=[('ZAKON', 'Zakonodaja'), ('STROKA', 'Pravila stroke'), ('PRAKSA', 'Gradbena praksa'), ('ZNANOST', 'Znanstvena dognanja'), ('ZDRUZENJA', 'Priporočila združenj'), ('IZVAJALCI', 'Priporočila izvajalcev')], default=podrobnosti.models.Podlaga('Pravila stroke'), max_length=10),
        ),
        migrations.DeleteModel(
            name='Dokumentacija',
        ),
        migrations.AddField(
            model_name='vir',
            name='slika',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Slika'),
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='vir',
            field=models.ManyToManyField(blank=True, to='podrobnosti.Vir'),
        ),
    ]
