# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podrobnosti', '0010_podrobnost_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podrobnost',
            name='datum',
            field=models.DateField(blank=True),
        ),
    ]
